augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: true
    maxpool_last2: false
    negative_slope: 0.2
  name: Conv64F
batch_size: 128
classifier:
  kwargs: null
  name: ProtoNet
data_root: data/DF20
dataloader_num: 1
deterministic: true
device_ids: 0
episode_size: 1
epoch: 50
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Proto.yaml
- backbones/Conv64F.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.01
  name: Adam
  other: null
parallel_part:
- emb_func
port: 33210
pretrain_path: null
query_num: 15
rank: 0
result_root: ./resultsDF20
resume: false
save_interval: 10
save_part:
- emb_func
seed: 2147483647
shot_num: 5
tag: null
tb_scale: 1.0
test_episode: 100
test_epoch: 5
test_query: 15
test_shot: 5
test_way: 5
train_episode: 100
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 2
